name: Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: zinchenkomig/bu_frontend:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.AUTH_TOKEN }}
          command_timeout: 15m
          script: |
            if cd front; then git pull; else git clone https://github.com/zinchenkomig/base-users-frontend.git front; cd front; fi
            cd k8s
            KUBECONFIG=/etc/rancher/k3s/k3s.yaml helm upgrade front scratch-front/ -i